### ISSUE TITLE
Decimal Multipliers are not possible

### ISSUE THREAD

**Issue by spencers145** [GMFelixfex/MultiCash#3]
The description notes that you may use Decimal Multipliers to make things harder. This is not the case:

https://github.com/GMFelixfex/MultiCash/blob/8d11796160953c4a093331ab54aa19830b698672/Multicash.cs#L210

For example, a x0.5 multiplier is parsed into x5.

**Comment by spencers145** [comment]
This is still possible via editing the config directly, but any attempt to edit it while in-game will not parse decimal values properly.

**Comment by GMFelixfex** [comment]
Propably should have closed this issue by now as it works as intented. The parse function just checks that even a "," gets correctly used.
